## Mouse
MBTN_LEFT_DBL    cycle fullscreen
MBTN_LEFT        ignore
MBTN_RIGHT       script-binding select/context-menu

## Media keys 
PLAY             cycle pause
PAUSE            cycle pause
PLAYPAUSE        cycle pause

NEXT             playlist-next
PREV             playlist-prev
MUTE             osd-msg cycle mute
VOLUME_UP        osd-msg add volume 2
VOLUME_DOWN      osd-msg add volume 2

FORWARD          osd-msg-bar seek  10 relative+exact
REWIND           osd-msg-bar seek -10 relative+exact

CLOSE_WIN        quit

## Arrows 
RIGHT            osd-msg-bar seek  2 relative+exact
LEFT             osd-msg-bar seek -2 relative+exact
UP               osd-msg add volume 2
DOWN             osd-msg add volume -2

## Numpad
KP9              playlist-next
KP7              playlist-prev

KP6              osd-msg-bar seek  2 relative+exact
KP4              osd-msg-bar seek -2 relative+exact

KP8              osd-msg add volume 2
KP2              osd-msg add volume -2

KP5              cycle fullscreen

KP_INS           cycle pause

KP_ENTER         show-progress
KP_DEL           quit

## TKL Keys
SPACE            cycle pause

b                playlist-next
n                playlist-next
p                playlist-prev
PGDWN            playlist-next
PGUP             playlist-prev

m                osd-msg cycle mute

BS               osd-msg set speed 1.0

.                frame-step
,                frame-back-step

ENTER            show-progress
ESC              set fullscreen no
f                cycle fullscreen

Ctrl+p           script-binding select/select-playlist
Ctrl+o           script-binding open_file/open
Ctrl+s           script-binding open_file/add_subtitle
Ctrl+a           script-binding open_file/add_audio

i                script-binding stats/display-stats
I                script-binding stats/display-stats-toggle

g                ignore
g-c              script-binding console/enable
g-p              script-binding modernz/progress-toggle
g-m              script-binding select/menu

q                quit
Q                quit-watch-later

HOME             seek 0 absolute

F11              apply-profile Autofit-Normal
F12              apply-profile Autofit-Large

v                script-binding modernz/visibility

# Image viewer binds
WHEEL_UP         {image} script-binding positioning/cursor-centric-zoom  0.1
WHEEL_DOWN       {image} script-binding positioning/cursor-centric-zoom -0.1
0                {image} no-osd set video-align-y 0; no-osd set video-align-x 0

O                no-osd cycle-values osd-level 3 1
