deadzonesize=0.9
deadzone_hide=timeout

title=${filename/no-ext}
font=Roboto
layout=modern
icon_theme=fluent
icon_style=outline

show_window_title=yes
window_controls=yes
ontop_in_topbar=yes

show_title=yes
show_chapter_title=yes

sub_margins=yes
osd_margins=yes
dynamic_margins=yes

osc_on_seek=no
osc_on_start=no
showonpause=yes
keeponpause=bottombar

cache_info=yes
cache_info_speed=no

jump_buttons=yes
chapter_skip_buttons=no

playlist_button=yes
subtitles_button=yes
audio_tracks_button=yes

info_button=no
ontop_button=yes
screenshot_button=yes
loop_button=no
shuffle_button=no
speed_button=no
