title=${filename/no-ext}

layout=modern
icon_theme=fluent
icon_style=outline

osc_on_seek=no
osc_on_start=no

font=Montserrat
window_title_font_size=28
title_font_size=28
chapter_title_font_size=18
cache_info_font_size=16
time_font_size=20
tooltip_font_size=18
speed_font_size=20

show_window_title=yes
window_controls=yes

show_title=yes
show_chapter_title=yes

sub_margins=yes
osd_margins=yes
dynamic_margins=yes

showonpause=yes
keeponpause=yes

nibbles_top=no
nibbles_bottom=yes

cache_info=yes
cache_info_speed=no

jump_buttons=yes
chapter_skip_buttons=no

playlist_button=yes
subtitles_button=yes
audio_tracks_button=yes

info_button=no
ontop_button=yes
screenshot_button=yes
loop_button=no
shuffle_button=no
speed_button=no
