window_title=${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename/no-ext}}
title=${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename/no-ext}}

layout=modern
icon_theme=fluent
icon_style=outline
zones_hover_mode=independent

osc_on_seek=no
osc_on_start=no

font=Montserrat

show_window_title=yes
window_controls=yes

show_title=no
show_chapter_title=no

sub_margins=yes
osd_margins=yes
dynamic_margins=yes

showonpause=yes
keeponpause=yes

nibbles_top=no
nibbles_bottom=yes

cache_info=yes
cache_info_speed=no

jump_buttons=yes
chapter_skip_buttons=no

playlist_button=yes
subtitles_button=yes
audio_tracks_button=yes

info_button=no
ontop_button=yes
screenshot_button=yes
loop_button=no
shuffle_button=no
speed_button=no
