indicator_icon=pause
indicator_stay=yes
indicator_timeout=0.6

keybind_allow=yes
keybind_set=mbtn_left
keybind_mode=onpause
keybind_eof_disable=yes

icon_color=#FFFFFF
icon_border_color=#111111
icon_border_width=1.5
icon_opacity=40

rectangles_width=30
rectangles_height=80
rectangles_spacing=20

triangle_width=80
triangle_height=80

flash_play_icon=yes
flash_icon_timeout=0.3

themed_icons=no
icon_theme=fluent
theme_style=outline
themed_icon_size=80

mute_indicator=yes
mute_indicator_pos=top_right
mute_icon_size=40
